spring:
  thymeleaf:
    cache: false

  datasource:
    url: jdbc:sqlite:E:\\recv\\data.db
    username:
    password:
    driver-class-name: org.sqlite.JDBC

sfh:
  storagePath: "E:\\recv\\storage"
  exposedAddr: "http://127.0.0.1:12345/"